#!/usr/bin/env sh
commit_message_file=$1

get_branch_name() {
  git_ref=${HUSKY_GIT_PARAMS:-''}
  branch_name=${git_ref%% *}
  echo "${branch_name#refs/heads/}"
}

get_issue_number() {
  branch_name=$1
  regex='\/([0-9]+)'
  if [[ $branch_name =~ $regex ]]; then
    echo "${BASH_REMATCH[1]}"
  fi
}

branch_name=$(get_branch_name)
issue_number=$(get_issue_number "$branch_name")

if [[ -n "$issue_number" ]]; then
  commit_message=$(cat "$commit_message_file")
  if [[ $commit_message == type:* ]]; then
    sed -i "1s/type:/type: (#$issue_number)/" "$commit_message_file"
  else
    sed -i "1i type: (#$issue_number)" "$commit_message_file"
  fi
fi
