export const QUERY_KEY = {
  POSTS: 'posts',
  POST_DETAIL: 'postDetail',
  COMMENTS: 'comments',
  CATEGORIES: 'categories',
  USER_INFO: 'userInfo',
  PASSION_RANKING: 'passionRanking',
  POPULAR_RANKING: 'popularRanking',
  VOTE_STATISTICS: 'voteStatistics',
  REPORT: 'report',
  ALARM_CONTENT: 'contentAlarm',
  ALARM_REPORT: 'reportAlarm',
  REPORT_APPROVE_RESULT: 'reportApproveResult',
  NOTICE: 'notice',
};
