spring:
  datasource:
    url: jdbc:h2:~/test;AUTO_SERVER=true;MODE=MySQL
    username: sa

  jpa:
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect
    show-sql: true

    hibernate:
      ddl-auto: create

logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql:
              BasicBinder: TRACE

votogether:
  openapi:
    dev-url: http://localhost:8080
    prod-url: http://votogether.com

oauth:
  kakao:
    info:
      grant_type: ${GRANT_TYPE}
      client_id: ${CLIENT_ID}
      client_secret: ${CLIENT_SECRET}
      redirect_uri: ${REDIRECT_URI}
