name: Notify Pull Request Deadline

on:
  pull_request:
    types:
      - opened
    branches: ['dev']
    paths:
      - 'frontend/**'
      - 'backend/**'
      - '.github/**'

jobs:
  pull_request_open:
    runs-on: ubuntu-latest
    name: New pr to repo
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Get PR details
        id: pr
        run: |
          PR_JSON=$(curl -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" "${{ github.event.pull_request.url }}")
          echo "::set-output name=pr_json::$PR_JSON"

      - name: Set environment variable
        run: echo "PR_CREATED_AT_UTC=${{ github.event.pull_request.created_at }}" >> $GITHUB_ENV
      - name: Convert UTC to KST
        run: |
          UTC_TIME=$PR_CREATED_AT_UTC
          KST_TIME=$(date -u -d "$UTC_TIME 9 hour" "+%Y-%m-%dT%H:%M:%SZ")
          echo "PR_CREATED_AT_KST=$KST_TIME" >> $GITHUB_ENV

      - name: Calculate deadline
        id: deadline
        run: node .github/workflows/scripts/calculateDeadline.js
        env:
          PR_CREATED_AT_KST: ${{ env.PR_CREATED_AT_KST }}

      - name: Send Slack notification When FE PR
        if: ${{ startsWith(github.event.pull_request.changed_files, 'frontend/') }}
        uses: slackapi/slack-github-action@v1.24.0
        with:
          channel-id: ${{ secrets.SLACK_FE_CHANNEL }} # Slack 채널 ID
          payload: |
            {
                "text": "",
                "blocks": [
                    {
                        "type": "section",
                        "text": {
                            "type": "mrkdwn",
                            "text": "<${{  github.event.pull_request.html_url }}|${{ github.event.pull_request.title }}>\n코드리뷰 마감시간:${{ steps.deadline.outputs.DEADLINE }}"
                        }
                    }
                ]
            }
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_TOKEN }} # Slack 토큰

      - name: Send Slack notification When BE PR
        if: ${{ startsWith(github.event.pull_request.changed_files, 'backend/') }}
        uses: slackapi/slack-github-action@v1.24.0
        with:
          channel-id: ${{ secrets.SLACK_BE_CHANNEL }} # Slack 채널 ID
          payload: |
            {
                "text": "",
                "blocks": [
                    {
                        "type": "section",
                        "text": {
                            "type": "mrkdwn",
                            "text": "<${{  github.event.pull_request.html_url }}|${{ github.event.pull_request.title }}>\n코드리뷰 마감시간:${{ steps.deadline.outputs.DEADLINE }}"
                        }
                    }
                ]
            }
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_TOKEN }} # Slack 토큰
